name: 12-hours-cron
on:
  schedule:
    - cron: "0 */3 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Get menu data
        run: |
          CODE=`curl --request POST --url 'https://www.snusket.se/api/snusket/job' --header 'Authorization: ${{ secrets.API_SECRET_KEY }}' -o /dev/null -s -w "%{http_code}"`
          echo $CODE
          if [ $CODE!="200" ] 
          then
              echo "FAILURE"
          else
              echo "SUCCESS"
          fi
